# synced from @nextcloud/android-config

# SPDX-FileCopyrightText: 2022-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-FileCopyrightText: 2023 Álvaro Brey <alvaro@alvarobrey.com>
# SPDX-License-Identifier: GPL-3.0-or-later

name: Auto approve dependabot

on:
  pull_request_target:
    branches:
      - main
      - master
      - stable-*

permissions:
  contents: read

concurrency:
  group: dependabot-approve-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  auto-approve:
    name: Auto approve dependabot
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    permissions:
      # needed to approve the PR
      pull-requests: write

    steps:
      - uses: hmarr/auto-approve-action@f0939ea97e9205ef24d872e76833fa908a770363 # v4.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
