# synced from @nextcloud/android-config
name: Auto approve dependabot

on:
  pull_request_target:
    branches:
      - main
      - master
      - stable-*

permissions:
  contents: read

concurrency:
  group: dependabot-approve-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  auto-approve:
    name: Auto approve dependabot
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    permissions:
      # needed to approve the PR
      pull-requests: write

    steps:
      - uses: hmarr/auto-approve-action@44888193675f29a83e04faf4002fa8c0b537b1e4 # v3.2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
