# synced from @nextcloud/android-config
name: "Validate Gradle Wrapper"
on:
    pull_request:
        branches: [ master, stable-* ]
    push:
        branches: [ master, stable-* ]

# Declare default permissions as read only.
permissions: read-all

concurrency: 
  group: validate-gradle-wrapper-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
    validation:
        name: "Validation"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
            - uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4 # v1.1.0
