# file sync configuration for repo-file-sync-action

# SPDX-FileCopyrightText: 2022-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-FileCopyrightText: 2022-2023 Álvaro Brey <alvaro@alvarobrey.com>
# SPDX-License-Identifier: GPL-3.0-or-later

group:
  - repos: |
      nextcloud/android@master
      nextcloud/talk-android@master
      nextcloud/notes-android@main
    files:
      - source: config/workflows/
        dest: .github/workflows/

  - repos: |
      nextcloud/android-library@master
      nextcloud/android-common@main
    files:
      - source: config/workflows/
        dest: .github/workflows/
    exclude: |
      lib.sh
      lib.sh.license
      qa.yml
      QA_keystore.jks
      QA_keystore.jks.license
      uploadArtifact.sh

  - repos: |
      nextcloud/android-config@main
    files:
      - source: config/workflows/scorecard.yml
        dest: .github/workflows/scorecard.yml
