# file sync configuration for repo-file-sync-action
group:
  repos: |
    nextcloud/android@master
    nextcloud/talk-android@master
    nextcloud/android-library@master
    nextcloud/android-common@main
  files:
    - source: config/workflows/
      dest: .github/workflows/
    - source: config/dependabot.yml
      dest: .github/dependabot.yml
