name: Auto approve
on:
  pull_request_target:
    branches:
      - main

permissions:
  pull-requests: write

concurrency: 
  group: auto-approve-renovate-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@44888193675f29a83e04faf4002fa8c0b537b1e4 # v3.2.1
        if: github.actor == 'renovate[bot]'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
