name: Auto approve
on:
  pull_request_target:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@0902bf83c300168cda5cd6856731a0fcb0e731c2 # v3.2.0
        if: github.actor == 'renovate[bot]'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
